/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


public class admind extends javax.swing.JFrame {

    

  User u;

    public admind() {
        initComponents();
    }
    
        public admind(User u) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.u=u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnuserdetail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btnlogout = new javax.swing.JButton();
        btnbookreq = new javax.swing.JButton();
        btnvfeedback = new javax.swing.JButton();
        btnveh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(468, 330));
        getContentPane().setLayout(null);

        btnuserdetail.setText("Available User");
        btnuserdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserdetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnuserdetail);
        btnuserdetail.setBounds(50, 120, 130, 23);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("           ADMIN DASHBOARD");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 280, 50);

        Btnlogout.setText("LOG OUT");
        Btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Btnlogout);
        Btnlogout.setBounds(140, 270, 130, 23);

        btnbookreq.setText("Booking Request");
        btnbookreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookreqActionPerformed(evt);
            }
        });
        getContentPane().add(btnbookreq);
        btnbookreq.setBounds(230, 120, 130, 23);

        btnvfeedback.setText("View Feedback");
        btnvfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvfeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnvfeedback);
        btnvfeedback.setBounds(50, 190, 130, 23);

        btnveh.setText("View Vehicles");
        btnveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehActionPerformed(evt);
            }
        });
        getContentPane().add(btnveh);
        btnveh.setBounds(230, 190, 130, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/userd.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 310);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 220, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuserdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserdetailActionPerformed

this.setVisible(false);
userdisplayadm uda=new userdisplayadm(u);
uda.setVisible(true);
    }//GEN-LAST:event_btnuserdetailActionPerformed

    private void BtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlogoutActionPerformed
        Btnlogout.setVisible(true);
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_BtnlogoutActionPerformed

    private void btnbookreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookreqActionPerformed
       this.setVisible(false);
        
     Requestedparking rp = new Requestedparking(u);
        rp.setVisible(true);
    }//GEN-LAST:event_btnbookreqActionPerformed

    private void btnvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehActionPerformed
       this.setVisible(false);
        Viewvehicle vw = new Viewvehicle(u);
        vw.setVisible(true);
    }//GEN-LAST:event_btnvehActionPerformed

    private void btnvfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvfeedbackActionPerformed
      this.setVisible(false);
        viewfedback vf = new viewfedback(u);
        vf.setVisible(true);
    }//GEN-LAST:event_btnvfeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnlogout;
    private javax.swing.JButton btnbookreq;
    private javax.swing.JButton btnuserdetail;
    private javax.swing.JButton btnveh;
    private javax.swing.JButton btnvfeedback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
