/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.*;

/**
 *
 * @author Emad
 */
public class Login extends javax.swing.JFrame {

    signup sup = new signup();
    User u = new User();
    

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtupass = new javax.swing.JPasswordField();
        rbu = new javax.swing.JRadioButton();
        rba = new javax.swing.JRadioButton();
        btnsignin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(570, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       CAR PARKING SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 340, 38);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 120, 70, 20);
        getContentPane().add(txtuname);
        txtuname.setBounds(270, 110, 150, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 150, 70, 20);
        getContentPane().add(txtupass);
        txtupass.setBounds(270, 150, 149, 22);

        rbu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbu.setForeground(new java.awt.Color(255, 255, 255));
        rbu.setText("User");
        rbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuActionPerformed(evt);
            }
        });
        getContentPane().add(rbu);
        rbu.setBounds(270, 200, 60, 20);

        rba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rba.setForeground(new java.awt.Color(255, 255, 255));
        rba.setText("Admin");
        rba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbaActionPerformed(evt);
            }
        });
        getContentPane().add(rba);
        rba.setBounds(360, 200, 100, 20);

        btnsignin.setForeground(new java.awt.Color(0, 0, 255));
        btnsignin.setText("SIGN IN");
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignin);
        btnsignin.setBounds(430, 260, 100, 23);

        btnsignup.setForeground(new java.awt.Color(0, 0, 255));
        btnsignup.setText("SIGNUP");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup);
        btnsignup.setBounds(120, 260, 110, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/log.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(567, 300));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 570, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        boolean b = false;
        String UN = txtuname.getText();
        String UP = txtupass.getText();
        String r = "";
        if (rba.isSelected()) {
            r = u.loginUser(UN, UP, rba.getText());
            System.out.println(r);
            if ("Success".equals(r)) {
                JOptionPane.showMessageDialog(null, "LOGGED IN");
                u.getUserDetail(UN, UP);
                this.setVisible(false);
                admind ad = new admind(u);
                ad.setVisible(true);
            } else if ("Fail".equals(r)) {

                JOptionPane.showMessageDialog(null, "Invalid credentials");
            }
        } else if (rbu.isSelected()) {
            r = u.loginUser(UN, UP, rbu.getText());
            System.out.println(r);
            if ("Success".equals(r)) {
                JOptionPane.showMessageDialog(null, "LOGGED IN");
                u.getUserDetail(UN, UP);
                this.setVisible(false);
                userd ud = new userd(u);
                ud.setVisible(true);
            } else if ("Fail".equals(r)) {

                JOptionPane.showMessageDialog(null, "Invalid credentials");
            }
        }


    }//GEN-LAST:event_btnsigninActionPerformed

    private void rbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuActionPerformed
        rba.setSelected(false);
    }//GEN-LAST:event_rbuActionPerformed

    private void rbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbaActionPerformed
        rbu.setSelected(false);
    }//GEN-LAST:event_rbaActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        sup.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnsignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rba;
    private javax.swing.JRadioButton rbu;
    private javax.swing.JTextField txtuname;
    private javax.swing.JPasswordField txtupass;
    // End of variables declaration//GEN-END:variables
}
