/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;




public class userclassdisplay extends javax.swing.JFrame {

    
User u;
   

    public userclassdisplay() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public userclassdisplay(User u) {
        initComponents();
        this.u=u;
        System.out.println(u.firstname);
        setUserInfo();
    }
    public void setUserInfo(){
        txtusername.setText(u.username);
        txtfstname.setText(u.firstname);
        txtlstname.setText(u.lastname);
        txtemail.setText(u.email);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfstname = new javax.swing.JTextField();
        txtlstname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("USER DETAIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 11, 152, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 88, 25);

        txtusername.setEditable(false);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername);
        txtusername.setBounds(140, 73, 152, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 115, 80, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 156, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-MAIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 63, 15);

        txtfstname.setEditable(false);
        getContentPane().add(txtfstname);
        txtfstname.setBounds(140, 113, 152, 30);

        txtlstname.setEditable(false);
        getContentPane().add(txtlstname);
        txtlstname.setBounds(140, 154, 152, 30);

        txtemail.setEditable(false);
        getContentPane().add(txtemail);
        txtemail.setBounds(140, 200, 152, 30);

        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(289, 270, 90, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/userclass.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
     this.setVisible(false);
        userd ud=new userd(u);
        ud.setVisible(true);
        
//        userd ud = new userd(u);
//        this.setVisible(false);
//        ud.setVisible(true);
//        String uname = txtusername.getText();
//        boolean b = bk.userdisplay(uname);
//            txtname.setText(bk.name);
//            txtaddress.setText(bk.add);
//            txtno.setText(bk.pn);
//            txtemail.setText(bk.em);
//            JOptionPane.showMessageDialog(null, "USER DISPLAYED");
//            this.setVisible(false);
//            userd ud = new userd();
//            ud.setVisible(true);
//        } else {
//            JOptionPane.showMessageDialog(null, "ERROR");
//        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed

    }//GEN-LAST:event_txtusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfstname;
    private javax.swing.JTextField txtlstname;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
