/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


public class userd extends javax.swing.JFrame {

    

  User u;

    public userd() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
        public userd(User u) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.u=u;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnuserdetail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btnlogout = new javax.swing.JButton();
        btnusersub = new javax.swing.JButton();
        btnuserdate = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        btncheckout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(461, 307));
        getContentPane().setLayout(null);

        btnuserdetail.setText("User Detail");
        btnuserdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserdetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnuserdetail);
        btnuserdetail.setBounds(50, 90, 130, 23);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("           USER DASHBOARD");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 280, 50);

        Btnlogout.setText("LOG OUT");
        Btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Btnlogout);
        Btnlogout.setBounds(240, 220, 130, 23);

        btnusersub.setText("Subscrption");
        btnusersub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersubActionPerformed(evt);
            }
        });
        getContentPane().add(btnusersub);
        btnusersub.setBounds(240, 90, 130, 23);

        btnuserdate.setText("Request");
        btnuserdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnuserdate);
        btnuserdate.setBounds(50, 150, 130, 30);

        btnfeedback.setText("Feedback");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnfeedback);
        btnfeedback.setBounds(240, 150, 130, 30);

        btncheckout.setText("CheckOut");
        btncheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckout);
        btncheckout.setBounds(50, 220, 130, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/userd.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 310);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 220, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuserdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserdetailActionPerformed
//        ucd=new userclassdisplay(u);
//        ucd.setVisible(true);
//        this.setVisible(false);
        this.setVisible(false);
        userclassdisplay ucd=new userclassdisplay(u);
        ucd.setVisible(true);
    }//GEN-LAST:event_btnuserdetailActionPerformed

    private void BtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlogoutActionPerformed
        Btnlogout.setVisible(true);
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_BtnlogoutActionPerformed

    private void btnusersubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersubActionPerformed
        this.setVisible(false);
        subscription s = new subscription(u);
        s.setVisible(true);
                        
    }//GEN-LAST:event_btnusersubActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        this.setVisible(false);
        userfedback uf=new userfedback(u);
        uf.setVisible(true);
                
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnuserdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserdateActionPerformed
        this.setVisible(false);
        Request rq=new Request(u);
        rq.setVisible(true);
    }//GEN-LAST:event_btnuserdateActionPerformed

    private void btncheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckoutActionPerformed
       this.setVisible(false);
        Checkout c=new Checkout(u);
        c.setVisible(true);
    }//GEN-LAST:event_btncheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnlogout;
    private javax.swing.JButton btncheckout;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JButton btnuserdate;
    private javax.swing.JButton btnuserdetail;
    private javax.swing.JButton btnusersub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
